version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: greenlight_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: greenlight
    ports:
      - "5432:5432"
    volumes:
      - greenlight_db:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  greenlight_db:

networks:
  postgres_network:
    driver: bridge
